;Copyright 2024 by Robert Sellers under the 2 clause BSD License.

; Vera registers.
vera_addr_low		= $9f20
vera_addr_high		= $9f21
vera_addr_bank		= $9f22
vera_data0			= $9f23
vera_data1			= $9f24
vera_ctrl			= $9f25
vera_ien			= $9f26
vera_isr			= $9f27

vera_dc_video		= $9f29
vera_dc_hscale		= $9f2a
vera_dc_vscale		= $9f2b

vera_L0_config		= $9f2d
vera_L0_mapbase		= $9f2e
vera_L0_tilebase	= $9f2f
vera_L0_hscroll_l	= $9f30
vera_L0_hscroll_h	= $9f31
vera_L0_vscroll_l	= $9f32
vera_L0_vscroll_h	= $9f33

vera_L1_config		= $9f34
vera_L1_mapbase		= $9f35
vera_L1_tilebase	= $9f36
vera_L1_hscroll_l	= $9f37
vera_L1_hscroll_h	= $9f38
vera_L1_vscroll_l	= $9f39
vera_L1_vscroll_h	= $9f3a
