
all:
	cl65 -t none -C lib_1.cfg -o lib_1.bin -l lib_1.list -Ln lib_1.sym \
	asm/main.asm asm/sprite.asm asm/math.asm asm/text.asm asm/sz.asm \
	asm/ctl.asm asm/ctl_edit.asm asm/meta.asm
	rm -f asm/*.o