;Copyright 2023 by Robert Sellers under the 2 clause BSD License.

CURSOR_ON       = $01

.ifndef _EDIT_ASM_

.import edit_cur_char
.import edit_color
.import edit_cursor_x
.import edit_cursor_y
.import edit_block_x
.import edit_block_y
.import edit_vram_cursor

.import edit_blink_cursor 
.import edit_set_vram_cursor
.import edit_display_vram_cursor
.import edit_clear_vram_cursor
.import edit_set_vram_block
.import edit_display_vram_block
.import edit_clear_vram_block
.import edit_process
.import edit_set_bg_color
.import edit_init

.endif	

