;Copyright 2023 by Robert Sellers under the 2 clause BSD License.

.ifndef _AREA_ASM_

.import area_
.import area_loaded

.import area_cur_format
.import area_cur_map
.import area_format_8_8
.import area_format_8_16
.import area_format_16_8
.import area_format_16_16
.import area_map_8_8
.import area_map_8_16
.import area_map_16_8
.import area_map_16_16

.import area_win_id
.import area_base_sze
.import area_base_def
.import area_cur_color
.import area_back_color
.import area_cur_tile
.import area_clipboard
.import area_base
.import area_wide
.import area_high
.import area_raw_x
.import area_raw_y
.import area_index
.import area_tile_x
.import area_tile_y

.import area_win_over
.import area_translate_color
.import area_set_cur_tile
.import area_reset_cur_tile
.import area_page_up 
.import area_page_down 
.import area_set_wide 
.import area_set_high 
.import area_set_raw_from_tile
.import area_background
.import area_init_border_sprites
.import area_init_borders
.import area_init_border_map
.import area_data_init 
.import area_init

.endif