;Copyright 2023 by Robert Sellers under the 2 clause BSD License.

.ifndef _DATA_ASM_

.import data_num_tiles
.import data_shift_tiles
.import data_num_borders

.import data_bpp
.import data_width
.import data_height
.import data_num_frames

.import data_shift_width
.import data_shift_height
.import data_load_offset

.import data_load_file
.import data_load_mouse_left

.import data_save_pixel
.import data_load_tile
.import data_load_tiles
.import data_delete_tile
.import data_copy_tile
.import data_paste_tile
.import data_left_arrow
.import data_right_arrow
.import data_up_arrow
.import data_down_arrow
.import data_init_clear_tiles
.import data_data_init
.import data_init

.endif